import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";

import { NuqsAdapter } from 'nuqs/adapters/next/app'

import {  TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],});
// This sets the page title (PunchCart) and description (used by Google, social previews, etc.).
export const metadata: Metadata = {
  title: "PunchCart",
  description: "Generated by Kanchankumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={dmSans.className} //apply global font 
      >
{/* NuqsAdapter:
Makes the Nuqs library work.
Nuqs lets you store React state inside the URL query string.
Example: If you have a filter/search bar, the values can sync to the URL like ?search=shirt&page=2.
Without Nuqs, you’d manage this manually. */}
        <NuqsAdapter>
        <TRPCReactProvider>
{/* Sets up tRPC client so all your React components can call the backend APIs directly with full type-safety. 
const products = api.product.getAll.useQuery();
This works because you wrapped your app in TRPCReactProvider.
*/}
        {children}
        <Toaster/>
        </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
