import type { Metadata } from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Application root layout component.
 *
 * Renders the top-level <html lang="en"> and a <body> that applies the DM Sans font class and global styles,
 * and injects the provided `children` as the page content.
 *
 * @param children - Content to render inside the body of the document.
 * @returns The root React element used as the app layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={dmSans.className}
      >
        {children}
      </body>
    </html>
  );
}
